trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.9'
    architecture: 'x64'

- bash: |    
    pip install --target="./.python_packages/lib/site-packages" -r ./requirements.txt
  displayName: 'Install dependencies'

# Run linting and generate report
- bash: |
    pip install flake8 flake8-html
    flake8 . --format=html --htmldir=flake8-report
  displayName: 'Run linting and generate report'
  continueOnError: true

# Run static analysis and generate report
- bash: |
    pip install bandit
    bandit -r . -f html -o bandit-report.html
  displayName: 'Run static analysis and generate report'
  continueOnError: true

# Archive files
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.Repository.LocalPath)'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    artifactName: 'drop'
    publishLocation: 'Container'

# Publish linting report
- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: 'flake8-report'
    artifactName: 'flake8-report'
    publishLocation: 'Container'

# Publish static analysis report
- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: 'bandit-report.html'
    artifactName: 'bandit-report'
    publishLocation: 'Container'