trigger:

- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.11'
    addToPath: true

- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
  displayName: 'Install dependencies'

- script: |
    echo "Listing files in the default working directory:"
    ls -al $(System.DefaultWorkingDirectory)
  displayName: 'List files in default working directory'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true
  displayName: 'Archive files'

- script: |
    echo "Listing files in the artifact staging directory:"
    echo "$(Build.ArtifactStagingDirectory)" 
    ls -al "$(Build.ArtifactStagingDirectory)"
    ls -al '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
  displayName: 'List files in artifact staging directory'

- script: |
    echo "Listing contents of the zip file:"
    unzip -l $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
  displayName: 'List contents of zip file'
  
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
  displayName: 'Publish artifacts'


- task: AzureFunctionApp@2
  inputs:
    connectedServiceNameARM: 'Azure subscription 1(6a57fd18-defb-4a17-b157-7898f92e4a74)'
    appType: 'functionAppLinux'
    appName: 'shop-function'
    package: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    runtimeStack: 'PYTHON|3.11'
    deploymentMethod: 'auto'

- script: |
    echo "Validating deployment..."
    curl -X GET "https://shop-function.azurewebsites.net/api/shop-function"
  displayName: 'Validate deployment'